language: python
python:
  - "3.5"
before_install:
  - export PIP_USE_MIRRORS=true
#  - export PIP_INDEX_URL=https://simple.crate.io/
#  - sudo apt-get update
install:
  - pip install -e .
  - pip install Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.9.12
branches:
  only:
    - develop
